# Generated by Django 5.1.3 on 2025-03-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_iftar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
