# Generated by Django 5.1.3 on 2025-03-25 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='iftar',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
