# Generated by Django 5.1.3 on 2025-03-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_iftar_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iftar',
            options={'ordering': ['-time'], 'verbose_name': 'IFTAR', 'verbose_name_plural': 'IFTARs'},
        ),
        migrations.RemoveField(
            model_name='iftar',
            name='start_date',
        ),
    ]
